// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDemoMVC.DbContexts;

#nullable disable

namespace TestDemoMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241005135330_Add_Employee_Props")]
    partial class Add_Employee_Props
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestDemoMVC.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Column1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
